# Generated by Django 2.2.4 on 2019-10-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('cryptocurrency', models.CharField(max_length=100, verbose_name='Cryptomoeda')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('image', models.ImageField(blank=True, null=True, upload_to='reports/images', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Cryptomoeda',
                'verbose_name_plural': 'Cryptomoedas',
                'ordering': ['cryptocurrency'],
            },
        ),
    ]
